### PR TITLE
Enhanced multiple projects' styling.

### PR DESCRIPTION
**Pull request by RishabhJain0721**

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@RishabhJain0721 give the screenshot of the changes, that you have done

**Comment by RishabhJain0721** [comment]
## Hi
Here I restyled the clicks counter website and also gave the ***Click here*** button animations.

Screenshot (13)
#

Enhanced the styling of **Lorem Ipsum Generator**.

Screenshot (14)
Screenshot (15)
#
Added the social media icons in ***Product Launching*** website along with media query.

Screenshot 2022-10-09 095235
Screenshot 2022-10-09 095352

**Comment by RishabhJain0721** [comment]
@Subhradeep10 Here are the changes that I made.

**Review by Subhradeep10 — APPROVED** [review]
Okkk

**Comment by RishabhJain0721** [comment]
Thank you :)

**Pull request merged**
